name: "ESLint"
on: [pull_request]
jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install dependencies
        run: pnpm install -r
      - name: Run ESLint
        run: pnpm lint
