name: "TypeScript"
on: [pull_request]
jobs:
  tests_e2e:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Initialize Yarn and install package dependencies
        run: yarn
      - name: Run TSC
        run: yarn typescript